
title: Jeececab's portfolio
email: jcseguincabana@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the portfolio of Jean-Christophe Séguin Cabana, front-end developper in process. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "jeececab.github.io" # the base hostname & protocol for your site
twitter_username: jeececab
github_username:  jeececab

# Build settings
markdown: kramdown
